### ISSUE TITLE
Git authentication error

### ISSUE THREAD

**Issue by jjonescz** [karma994/ClickOnceInstaller#1]
Replying to your comment under https://janjones.me/posts/clickonce-installer-build-publish-github/.

So it seems like a problem with credentials here:

https://github.com/karma994/ClickOnceInstaller/blob/dca8657808efe364df894bfe1797534e93575bf7/.github/workflows/release.yml#L17

I'm not sure what's exactly the problem, but can you use just `GITHUB_TOKEN` instead of `CUSTOM_GITHUB_TOKEN`? That works for me.

**Comment by karma994** [comment]
Thank you it worked when i use GITHUB_TOKEN, but at last when i download and try to open application its giving me error saying  this "Cannot download application, its  missing required files."

error details here "PLATFORM VERSION INFO
	Windows 			: 10.0.19045.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9176.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9181.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9176.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.19041.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///D:/WPF_ClickOnce.application
	Deployment Provider url		: https://github.com/karma994/ClickOnceInstaller/WPF_ClickOnce.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\WPF_ClickOnce.application resulted in exception. Following failure messages were detected:
		+ Downloading https://github.com/karma994/ClickOnceInstaller/WPF_ClickOnce.application did not succeed.
		+ The remote server returned an error: (404) Not Found.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [12/2/2023 12:01:47 PM] : Activation of D:\WPF_ClickOnce.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/2/2023 12:01:48 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://github.com/karma994/ClickOnceInstaller/WPF_ClickOnce.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (404) Not Found.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

"

**Comment by jjonescz** [comment]
Seems you have wrong URL in your publish profile:

https://github.com/karma994/ClickOnceInstaller/blob/085843269ea123c8321bd5d03d7f8e03f762fa17/WPF_ClickOnce/Properties/PublishProfiles/ClickOnceProfile.pubxml#L15

It should be https://karma994.github.io/ClickOnceInstaller/
